Controllers/CalculationController.cs
using ApartmanProjeMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApartmanProjeMVC.Controllers
{
    public class CalculationController : Controller
    {
        public ViewResult IslemTablo(string search)
        {

            using (ApartmanYonetimEntities baglan = new ApartmanYonetimEntities())
            {
                List<Uyeler> uyeler = baglan.Uyeler.ToList();
                List<Islemler> islemler = baglan.Islemler.ToList();

                var islemKayit = from e in islemler

                                 join d in uyeler on e.UyeId equals d.ID into table1
                                 from d in table1.ToList()

                                 select new ViewModel
                                 {
                                     islemler = e,
                                     uyeler = d,

                                 };

                var uyeTablo = uyeler;
                var islemTablo = islemler;
                ViewBag.uyeler = uyeTablo;
                ViewBag.islemler = islemTablo;
                Int32 uyeID = uyeTablo[0].ID;
                Int32 islemID = islemTablo[0].id;
                if (!String.IsNullOrEmpty(search))
                {
                    islemKayit = islemKayit.Where(s => s.islemler.UyeId == Convert.ToInt32(search));

                }
                
                return View(islemKayit);
            }
        }

        public ActionResult IslemEkle()
        {
            using (ApartmanYonetimEntities baglan = new ApartmanYonetimEntities())
            {
                var uyeTablo = baglan.Uyeler.ToList();
                ViewBag.uyeler = uyeTablo;

                Int32 uyeID = uyeTablo[0].ID;
                return View();
            }


        }

        [HttpPost]
        public ActionResult IslemEkle(Islemler islem)
        {
            using (ApartmanYonetimEntities baglan = new ApartmanYonetimEntities())
            {
                if ((islem.Tutar != null)&& (islem.Aciklama != null))
                {

                    baglan.Islemler.Add(islem);
                    baglan.SaveChanges();
                    Session["uyari"] = "Bilgileriniz kaydedildi.";
                }
                else
                {
                    Session["uyari"] = "Gerekli alanları doldurunuz ";
                }
                return RedirectToAction("IslemTablo");
            }

        }
    }

    
}

Views/Calculation/IslemEkle.cshtml
@model ApartmanProjeMVC.Models.Islemler
@{
               

                ViewBag.Title = "IslemEkle";
                Layout = "~/Views/Shared/Yonetim.cshtml";
}

<h2>IslemEkle</h2>
@using (Html.BeginForm("IslemEkle", "Calculation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>
                @Html.DropDownList("UyeId", new SelectList(ViewBag.uyeler, "id", "Ad"), new { @class = "form-control", onchange = "AdSec()" })
            </td>


            <td>
                @Html.TextBoxFor(m => m.Tutar, new { @class = "form-control", placeholder = "Tutar" })

            </td>

            
            <td>
                @Html.TextBoxFor(m => m.Aciklama, new { @class = "form-control", placeholder = "Açıklama" })
            </td>
            <td>
                <button type="submit" class="btn btn-success">Ekle</button>

                <hr />
                <p>@ViewBag.uyari</p>
            </td>
        </tr>
    </table>
}

Views/Calculation/IslemTablo.cshtml
@model IEnumerable<ApartmanProjeMVC.Models.ViewModel>
@{
    ViewBag.Title = "IslemTablo";
    Layout = "~/Views/Shared/Yonetim.cshtml";
}

<h2>IslemTablo</h2>

<!DOCTYPE html>

<html>
@using (Html.BeginForm("IslemTablo", "Calculation", FormMethod.Get))
{


    <body>


        <table>
            <tr>
                <td>
                    @Html.DropDownList("search", new SelectList(ViewBag.uyeler, "id", "Ad"), new { @class = "form-control" })

                </td>
                
                <td>
                    <input type="submit" name="btnSubmit" value="Submit" />
                </td>
            </tr>

        </table>



        <div class="container-fluid py-4">

            <table class="table table-striped table-bordered">
                <thead class="bg-dark text-white">
                    <tr>
                        <th>Ad Soyad</th>
                        <th>Daire  No</th>
                        <th>Tutar</th>
                        <th>Tarih</th>
                        <th>Açıklama</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(m => item.uyeler.Ad)</td>
                            <td>@Html.DisplayFor(m => item.uyeler.Daire)</td>
                            <td>@Html.DisplayFor(m => item.islemler.Tutar)</td>
                            <td>@Html.DisplayFor(m => item.uyeler.tarih)</td>
                            <td>@Html.DisplayFor(m => item.islemler.Aciklama)</td>

                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </body>
}
</html>