Models/Uyeler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanProjeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<int> Daire { get; set; }
        public string Oturan { get; set; }
        public string gsm { get; set; }
        public string Bakiye { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}

Controllers/UyelerController.cs
using ApartmanProjeMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApartmanProjeMVC.Controllers
{
    
    public class UyelerController : Controller
    {
        ApartmanYonetimEntities baglan = new ApartmanYonetimEntities();
        public ActionResult Liste()
        {
            try
            {
                ViewBag.uyarTXT = Session["uyari"];
            }
            catch
            { Session["uyari"] = ""; }
            List<object> otur = new List<object>();

            otur.Add(new SelectListItem { Text = "Ev Sahibi", Value = "Ev Sahibi" });
            otur.Add(new SelectListItem { Text = "Kiracı", Value = "Kiracı" });

            ViewBag.oturan = otur;
            var model = baglan.Uyeler.ToList();
            return View(model);
        }
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Uyeler ekle)
        {
            if ((ekle.Ad != null) && (ekle.gsm != null))
            {
                baglan.Uyeler.Add(ekle);
                baglan.SaveChanges();
                Session["uyari"] = "Bilgileriniz kaydedildi.";
            }
            else
            {
                Session["uyari"] = "Gerekli alanları doldurunuz ";
            }
            return RedirectToAction("Liste");
        }
        [HttpPost]
        public JsonResult Degisim(Uyeler uyedeg)
        {

            var degisim = baglan.Uyeler.Find(uyedeg.ID);
            degisim.Ad = uyedeg.Ad;
            degisim.Daire = uyedeg.Daire;
            if (uyedeg.Oturan != null)
            { degisim.Oturan = uyedeg.Oturan; }
            degisim.gsm = uyedeg.gsm;
            degisim.tarih = uyedeg.tarih;

            baglan.SaveChanges();
            return Json("Bilgileriniz güncellendi", JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Sil(int id)
        {

            var silinecek = baglan.Uyeler.Find(id);
            baglan.Uyeler.Remove(silinecek);

            baglan.SaveChanges();
            return Json("Silme işlemi tamamlandı.", JsonRequestBehavior.AllowGet);
        }

    }
}

Views/Uyeler/Ekle.cshtml
@model ApartmanProjeMVC.Models.Uyeler
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/Yonetim.cshtml";
}

<h2>Ekle</h2>

@using (Html.BeginForm("Ekle", "Uyeler", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>
                @Html.TextBoxFor(m => m.Ad, new { @class = "form-control", placeholder = "Ad ve Soyad" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.Daire, new { @class = "form-control", placeholder = "Daire numarası" })
            </td>
            <td>
                <div>
                    <select name="oturan" class="btn btn-success" style="width:100%">
                        <option value="Ev Sahibi">Ev Sahibi</option>
                        <option value="Kiracı">Kiracı</option>
                    </select>
                </div>
            </td>
            <td>
                @Html.TextBoxFor(m => m.gsm, new { @class = "form-control", placeholder = "Telefon numarası" })
            </td>

            <td>
                @Html.TextBoxFor(m => m.tarih, new { @class = "form-control", placeholder = "Tarih", @type = "date" })
            </td>
            <td>
                <button type="submit" class="btn btn-success">Ekle</button>
                <hr />
                <p>@ViewBag.uyari</p>
            </td>
        </tr>
    </table>
}

Views/Uyeler/Liste.cshtml
@model List<ApartmanProjeMVC.Models.Uyeler>
@{
    ViewBag.Title = "Liste";
    Layout = "~/Views/Shared/Yonetim.cshtml";
}

<h2>Liste</h2>

<table>
    <thead>
        <tr>
            <td>
                ID
            </td>
            <td>
                Ad-Soyad
            </td>
            <td>
                Daire Numarası
            </td>
            <td>
                Oturan Kişi
            </td>
            <td>
                Telefon Numarası
            </td>

            <td>
                Tarih
            </td>
            <td>
                Bakiye
            </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var uye in Model)
        {
            <tr id="tablo_@uye.ID">
                <td>
                    <input id="@uye.ID" type="text" value="@uye.ID" class="form-control" readonly />
                </td>
                <td>
                    <input id="adsoyad_@uye.ID" type="text" value="@uye.Ad" class="form-control" />
                </td>
                <td>
                    <input id="daire_@uye.ID" type="text" value="@uye.Daire" class="form-control" />
                </td>
                <td>
                    @Html.DropDownList("oturan_" + uye.ID, new SelectList(ViewBag.oturan, "Value", "Text"), uye.Oturan, new { @class = "form-control" })
                </td>
                <td>
                    <input id="gsm_@uye.ID" type="text" value="@uye.gsm" class="form-control" />
                </td>

                <td>
                    <input id="tarih_@uye.ID" type="datetime" value="@uye.tarih" class="form-control" />
                </td>
                <td>
                    <input type="text" value="@uye.Bakiye" class="form-control" readonly />
                </td>
                <td>
                    <button type="button" class="btn btn-warning" onclick="UyeDegistir(@uye.ID)">Değiştir</button>
                </td>
                <td>
                    <button type="button" class="btn btn-danger" onclick="UyeSil(@uye.ID)">Sil</button>
                </td>

            </tr>
        }
    </tbody>
</table>